// JavaScript Document

$(function() {
  $(".spritespin1").spritespin({
    source: [
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B00.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B01.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B02.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B03.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B04.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B05.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B06.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B07.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B08.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B09.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B10.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B11.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B12.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B13.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B14.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B15.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B16.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B17.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B18.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B19.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B20.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B21.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B22.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B23.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B24.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B25.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B26.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B27.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B28.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B29.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B30.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B31.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B32.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B33.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B34.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B35.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B36.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B37.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B38.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B39.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B40.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B41.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B42.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B43.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/03%20B%26B44.png",
    ],
    width: 480,
    height: 327,
    // reverse interaction direction
    sense: -1
  });
})
  
$(function() {
  $(".spritespin2").spritespin({
    source: [
       "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita00.png",
       "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita01.png",
       "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita02.png",
       "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita03.png",
       "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita04.png",
       "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita05.png",
       "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita06.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita07.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita08.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita09.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita10.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita11.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita12.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita13.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita14.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita15.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita16.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita17.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita18.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita19.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita20.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita21.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita22.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita23.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita24.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita25.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita26.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita27.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita28.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita29.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita30.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita31.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita32.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita33.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita34.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita35.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita36.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita37.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita38.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita39.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita40.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita41.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita42.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita43.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita44.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita45.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita46.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita47.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita48.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita49.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita50.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita51.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita52.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita53.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita54.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita55.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita56.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita57.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita58.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita59.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita60.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita61.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita62.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita63.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita64.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita65.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita66.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita67.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita68.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita69.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita70.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita71.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita72.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita73.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita74.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita75.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita76.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita77.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita78.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita79.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita80.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita81.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita82.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/02%20Cajita83.png",
    ],
    width: 480,
    height: 327,
    // reverse interaction direction
    sense: -1
  });
})

$(function() {
  $(".spritespin3").spritespin({
    source: [
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM00.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM01.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM02.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM03.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM04.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM05.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM06.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM07.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM08.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM09.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM10.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM11.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM12.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM13.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM14.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM15.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM16.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM17.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM18.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM19.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM20.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM21.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM22.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM23.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM24.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM25.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM26.png",
      "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/05%20CREAM27.png",
      
    ],
    width: 480,
    height: 327,
    // reverse interaction direction
    sense: -1
  });
})

$(function() {
  $(".spritespin4").spritespin({
    source: [
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_100.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_101.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_102.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_103.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_104.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_105.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_106.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_107.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_108.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_109.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_110.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_111.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_112.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_113.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_114.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_115.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_116.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_117.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_118.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_119.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_120.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_121.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_122.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_123.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_124.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_125.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_126.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_127.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_128.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_129.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_130.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_131.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_132.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_133.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_134.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_135.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_136.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_137.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_138.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_139.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_140.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_141.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_142.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_143.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_144.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_145.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_146.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_147.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_148.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_149.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_150.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_151.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_152.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_153.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_154.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_155.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_156.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_157.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_158.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_159.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_160.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_161.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_162.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_163.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_164.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_165.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_166.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_167.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_168.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_169.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_170.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_171.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_172.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_173.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_174.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_175.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_176.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_177.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_178.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_179.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_180.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_181.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_182.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_183.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_184.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_185.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_186.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_187.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_188.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_189.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_190.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_191.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_192.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/01%20Gitana-_193.png",
    ],
    width: 480,
    height: 327,
    // reverse interaction direction
    sense: -1
  });
})

$(function() {
  $(".spritespin5").spritespin({
    source: [
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea00.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea01.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea02.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea03.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea04.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea05.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea06.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea07.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea08.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea09.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea10.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea11.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea12.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea13.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea14.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea15.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea16.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea17.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea18.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea19.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea20.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea21.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea22.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea23.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea24.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea25.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea26.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea27.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea28.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea29.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea30.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea31.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea32.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea33.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea34.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea35.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea36.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea37.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea38.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea39.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea40.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea41.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/04%20Great%20Idea42.png",
    ],
    width: 480,
    height: 327,
    // reverse interaction direction
    sense: -1
  });
})

$(function() {
  $(".spritespin6").spritespin({
    source: [
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_100.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_101.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_102.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_103.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_104.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_105.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_106.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_107.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_108.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_109.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_110.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_111.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_112.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_113.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_114.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_115.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_116.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_117.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_118.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_119.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_120.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_121.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_122.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_123.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_124.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_125.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_126.png",
        "https://cdn.jsdelivr.net/gh/paudev17/spin-sprite-flowers/assets/img/06%20Holy%20Basil_127.png",
    ],
    width: 480,
    height: 327,
    // reverse interaction direction
    sense: -1
  });
})
